name: slack_notification
description: A simple wrapper to post messages from external sources into Slack.
version: 1.2.1
repository: https://github.com/huhx/slack_notification

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dio: ^5.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

